#!/bin/bash

# Create pull request for repository
gh pr create -R github.com/Xdantex0000/Test_Repository -B release -t "GH pull request" -b "Body of pull request"
gh pr create -R github.com/Xdantex0000/Test2_Repository -B release -t "GH pull request" -b "Body of pull request"
