name: Comment Commands

on:
  issue_comment:
    types: [created]

jobs:
  merge:
    name: Merge
    if: github.event.comment.body == '/merge'
    uses: Xdantex0000/Test_Repository/.github/workflows/labeled.yml@main