name: Comment Command

on:
  issue_comment:
    types:
      - created

jobs:
  merge:
    name: Merge
    if: github.event.comment.body == '/merge'
    uses: xdantex0000/test_repository/tree/main/.github/workflows/labeled.yml