name: Label on merge

on:
  workflow_call:

jobs:
  merge:
    if: github.event.comment.body == '/merge'
    name: Merge
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Repo
        run: echo ${{ github.event.issue.labels[0].name }}
        
# jobs:
#   merge:
#     if: github.event.comment.body == '/merge'
#     name: Merge
#     runs-on: ubuntu-latest
#     permissions:
#       issues: write
#     steps:
#       - uses: actions/github-script@v6
#         with:
#           script: |
#             echo github.rest.pulls.get({
#               owner: github.event.repo.owner,
#               repo: github.event.repo,
#               pull_number: github.event.issue.number,
#             })