name: Label on merge

on:
  workflow_call:

jobs:
  merge:
    if: github.event.comment.body == '/merge'
    name: Merge
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/github-script@v6
        run: echo context.repo.owner