name: Label on merge

on:
  workflow_call:

jobs:
  merge:
    if: github.event.comment.body == '/merge'
    name: Merge
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Owner
        run: echo context.repo.owner
        
      - name: Repo
        run: context.repo.repo